app:
  config:
    configServerHost: localhost
    
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_SERVER_HOST}/enrollment_mgmt_db_prod
    username: postgres
    password: XDWEKF4SDE8WDD25DS7WW6D02D
    