app:
  config:
    configServerHost: localhost
    
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/enrollment_mgmt_db_prod
      username: postgres
      password: XDWEKF4SDE8WDD25DS7WW6D02D
    