app:
  config:
    configServerHost: localhost
    hibernateImportFiles: load_user_script.sql, load_roles_scripts.sql
    
spring:
  datasource:
    hikari:
      jdbc-url:  jdbc:h2:mem:testdb
      username: sa
      password:
  